name: DiscordFileManager
version: '1.1.1'
main: me.amuazm.discordFileManager.DiscordFileManager
api-version: '1.20'
description: Discord File Manager for Minecraft Paper (Supports 1.20.2+)
author: amuazm
website: https://github.com/amuazm/DiscordFileManager
commands:
  dfm:
    description: Discord File Manager Commands
    usage: /dfm reload
    permission: discordfilemanager.reload
    permission-message: You don't have permission to use this command.
permissions:
  discordfilemanager.reload:
    description: Allows reloading the DiscordFileManager config
    default: op